#!/bin/bash

COMMAND=$1
while [[ "$#" -gt 0 ]]; do
    case $1 in
    --python-version)
        PYTHON_VERSION="$2"
        shift
        shift
        ;;
    *)
        COMMAND=$1
        shift
        break
        ;;
    esac
    shift
done

# =============================================================================

if [ $COMMAND == "build" ]; then
    docker build -f Dockerfile -t usalko/molog:1.0.1 . --progress=plain
fi

if [ $COMMAND == "publish" ]; then
    IMAGE=usalko/molog:1.0.1
    docker push "$IMAGE" || {
        echo "Line 12: Error in push to dockerhub image $IMAGE... Exit..."
        exit 1
    }
fi

if [ $COMMAND == "test" ]; then
    curl --data-binary @.test-data/12.23.23_00.09.58_809.zip http://localhost:8804/api/v1
fi

if [ $COMMAND == "test2" ]; then
    curl -F file=@.test-data/12.23.23_00.09.58_809.zip http://localhost:8804/api/v1
fi

if [ $COMMAND == "test3" ]; then
    curl --form-escape --form 'field\name=12.23.23_00.09.58_809.zip' 'file=@.test-data/12.23.23_00.09.58_809.zip' http://localhost:8804/api/v1
fi

# =============================================================================

if [ $COMMAND == "test0" ]; then
    curl -X POST http://promtail:3500/push/foo/bar/fizz/buzz -d "Hell, World!"
fi

