#!/bin/bash

COMMAND=$1
while [[ "$#" -gt 0 ]]; do
    case $1 in
    --python-version)
        PYTHON_VERSION="$2"
        shift
        shift
        ;;
    *)
        COMMAND=$1
        shift
        break
        ;;
    esac
    shift
done

# =============================================================================

if [ $COMMAND == "build" ]; then
    docker build -f Dockerfile -t usalko/molog:1.0.1 . --progress=plain
fi

if [ $COMMAND == "publish" ]; then
    IMAGE=usalko/molog:1.0.1
    docker push "$IMAGE" || {
        echo "Line 12: Error in push to dockerhub image $IMAGE... Exit..."
        exit 1
    }
fi

if [ $COMMAND == "test" ]; then
    curl --include \
        --no-buffer \
        --header "Connection: Upgrade" \
        --header "Upgrade: websocket" \
        --header "Host: localhost:8801" \
        --header "Origin: http://localhost:8801" \
        --header "Sec-WebSocket-Key: MTIzNDU2Nzg5MDEyMzQ1Ng==" \
        --header "Sec-WebSocket-Version: 13" \
        http://localhost:8801/ws
fi

